# Generated by Django 4.2.3 on 2023-08-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_detected',
            field=models.TextField(default='default'),
        ),
    ]
