# Generated by Django 4.2.3 on 2023-08-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mp4',
            field=models.FileField(null=True, upload_to='audio/'),
        ),
    ]
