# Generated by Django 4.2.3 on 2023-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_mp4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mp4',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
