# Generated by Django 4.2.3 on 2023-08-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_mp4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('en', 'english'), ('hi', 'hindi'), ('te', 'telugu'), ('ta', 'tamil'), ('mr', 'marati'), ('ml', 'malayalam'), ('mr', 'marati'), ('bn', 'bengali'), ('gu', 'gujarati'), ('kn', 'kannada'), ('ne', 'nepali'), ('ur', 'urdu')], default='en', max_length=2),
        ),
    ]
