# Generated by Django 4.2.3 on 2023-08-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_title_post_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instance_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
