# Generated by Django 4.2.3 on 2023-08-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_instance_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='instance_id',
        ),
    ]
