# Generated by Django 4.2.3 on 2023-08-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_instance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='mp4',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
